//
// Created by konek on 7/26/2019.
//

#ifndef GLNE_GLIS_H
#define GLNE_GLIS_H

#include <android/native_window.h> // requires ndk r5 or newer
#include <EGL/egl.h> // requires ndk r5 or newer
#include <GLES3/gl32.h>
#include <cstdlib>
#include <cassert>
#include <malloc.h>
#include <string>
#include <sys/socket.h>
#include <sys/un.h>
#include <cerrno>
#include <unistd.h>
#include <poll.h>

#include "logger.h"


#define LOG_TAG "EglSample"

std::string GLIS_INTERNAL_MESSAGE_PREFIX = "";

#define GLIS_SWITCH_CASE_CUSTOM_CASE_CUSTOM_LOGGER_CUSTOM_STRING_CAN_I_PRINT_ERROR(LOGGING_FUNCTION, CASE_NAME, name, const, constSTRING, UNNAMED_STRING_CAN_PRINT_ERROR, UNNAMED_STRING_CANNOT_PRINT_ERROR, NAMED_STRING_CAN_PRINT_ERROR, NAMED_STRING_CANNOT_PRINT_ERROR, PRINT) CASE_NAME: { \
    if(name == nullptr || name == NULL || name == 0) { \
        if (PRINT) { \
            if (UNNAMED_STRING_CAN_PRINT_ERROR != nullptr) { \
                std::string msg = GLIS_INTERNAL_MESSAGE_PREFIX; \
                msg += UNNAMED_STRING_CAN_PRINT_ERROR; \
                LOGGING_FUNCTION(msg.c_str(), constSTRING); \
            } \
        } \
        else { \
            if (UNNAMED_STRING_CANNOT_PRINT_ERROR != nullptr) { \
                std::string msg = GLIS_INTERNAL_MESSAGE_PREFIX; \
                msg += UNNAMED_STRING_CANNOT_PRINT_ERROR; \
                LOGGING_FUNCTION("%s", msg.c_str()); \
            } \
        } \
    } \
    else { \
        if (PRINT) { \
            if (NAMED_STRING_CAN_PRINT_ERROR != nullptr) { \
                std::string msg = GLIS_INTERNAL_MESSAGE_PREFIX; \
                msg += NAMED_STRING_CAN_PRINT_ERROR; \
                LOGGING_FUNCTION(msg.c_str(), name, constSTRING); \
            } \
        } \
        else { \
            if (NAMED_STRING_CANNOT_PRINT_ERROR != nullptr) { \
                std::string msg = GLIS_INTERNAL_MESSAGE_PREFIX; \
                msg += NAMED_STRING_CANNOT_PRINT_ERROR; \
                LOGGING_FUNCTION(msg.c_str(), name); \
            } \
        } \
    } \
    break; \
}


#define GLIS_SWITCH_CASE_CUSTOM_LOGGER_CUSTOM_STRING_DONT_PRINT_ERROR(LOGGER, name, const, constSTRING, UNNAMED_STRING, NAMED_STRING) \
    GLIS_SWITCH_CASE_CUSTOM_CASE_CUSTOM_LOGGER_CUSTOM_STRING_CAN_I_PRINT_ERROR(LOGGER, case const, name, const, constSTRING, nullptr, UNNAMED_STRING, nullptr, NAMED_STRING, false)
    
#define GLIS_SWITCH_CASE_CUSTOM_LOGGER_CUSTOM_STRING(LOGGER, name, const, constSTRING, UNNAMED_STRING, NAMED_STRING) \
    GLIS_SWITCH_CASE_CUSTOM_CASE_CUSTOM_LOGGER_CUSTOM_STRING_CAN_I_PRINT_ERROR(LOGGER, case const, name, const, constSTRING, UNNAMED_STRING, nullptr, NAMED_STRING, nullptr, true)

#define GLIS_ERROR_SWITCH_CASE_CUSTOM_STRING_DONT_PRINT_ERROR(name, const, constSTRING, UNNAMED_STRING, NAMED_STRING) \
    GLIS_SWITCH_CASE_CUSTOM_LOGGER_CUSTOM_STRING_DONT_PRINT_ERROR(LOG_ERROR, name, const, constSTRING, UNNAMED_STRING, NAMED_STRING)

#define GLIS_ERROR_SWITCH_CASE_CUSTOM_STRING(name, const, constSTRING, UNNAMED_STRING, NAMED_STRING) \
    GLIS_SWITCH_CASE_CUSTOM_LOGGER_CUSTOM_STRING(LOG_ERROR, name, const, constSTRING, UNNAMED_STRING, NAMED_STRING)

#define GLIS_ERROR_SWITCH_CASE(name, const) \
    GLIS_ERROR_SWITCH_CASE_CUSTOM_STRING(name, const, #const, "%s", "%s generated error: %s")

#define GLIS_ERROR_SWITCH_CASE_DEFAULT(name, err) \
    GLIS_SWITCH_CASE_CUSTOM_CASE_CUSTOM_LOGGER_CUSTOM_STRING_CAN_I_PRINT_ERROR(LOG_ERROR, default, name, err, err, "Unknown error: %d", "Unknown error", "%s generated an unknown error: %d", "%s generated an unknown error", true)

#define GLIS_boolean_to_string(val, TRUE_VALUE) val == TRUE_VALUE ? "true" : "false"

#define GLIS_SHADER_SOURCE__BEGIN R"glsl(
#define GLIS_SHADER_SOURCE__END )glsl";
#define GLIS_SHADER_SOURCE__(S, source, E) S source E
#define GLIS_SHADER_SOURCE(source) GLIS_SHADER_SOURCE__(GLIS_SHADER_SOURCE__BEGIN, source, GLIS_SHADER_SOURCE__END)

#define GLIS_error_to_string_exec(x) x; GLIS_error_to_string(#x)
#define GLIS_error_to_string_exec_GL(x) x; GLIS_error_to_string_GL(#x)
#define GLIS_error_to_string_exec_EGL(x) x; GLIS_error_to_string_EGL(#x)

void GLIS_error_to_string_GL(const char * name, GLint err) {
    GLIS_INTERNAL_MESSAGE_PREFIX = "OpenGL:          ";
    switch(err) {
        // GENERATED BY glGetError() ITSELF
        GLIS_SWITCH_CASE_CUSTOM_LOGGER_CUSTOM_STRING_DONT_PRINT_ERROR(LOG_INFO, name, GL_NO_ERROR, "GL_NO_ERROR", "no error was generated", "%s did not generate an error")
        GLIS_ERROR_SWITCH_CASE(name, GL_INVALID_ENUM)
        GLIS_ERROR_SWITCH_CASE(name, GL_INVALID_VALUE)
        GLIS_ERROR_SWITCH_CASE(name, GL_INVALID_OPERATION)
        GLIS_ERROR_SWITCH_CASE(name, GL_INVALID_FRAMEBUFFER_OPERATION)
        GLIS_ERROR_SWITCH_CASE(name, GL_OUT_OF_MEMORY)

        // WHEN ALL ELSE FAILS
        GLIS_ERROR_SWITCH_CASE_DEFAULT(name, err)
    }
    GLIS_INTERNAL_MESSAGE_PREFIX = "";
}

void GLIS_error_to_string_EGL(const char * name, EGLint err) {
    GLIS_INTERNAL_MESSAGE_PREFIX = "OpenGL ES (EGL): ";
    switch(err) {
        // GENERATED BY eglGetError() ITSELF
        GLIS_SWITCH_CASE_CUSTOM_LOGGER_CUSTOM_STRING_DONT_PRINT_ERROR(LOG_INFO, name, EGL_SUCCESS, "EGL_SUCCESS", "no error was generated", "%s did not generate an error")
        GLIS_ERROR_SWITCH_CASE(name, EGL_NOT_INITIALIZED)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_ACCESS)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_ALLOC)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_ATTRIBUTE)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_CONTEXT)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_CONFIG)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_CURRENT_SURFACE)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_DISPLAY)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_SURFACE)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_MATCH)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_PARAMETER)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_NATIVE_PIXMAP)
        GLIS_ERROR_SWITCH_CASE(name, EGL_BAD_NATIVE_WINDOW)
        GLIS_ERROR_SWITCH_CASE(name, EGL_CONTEXT_LOST)

        // WHEN ALL ELSE FAILS
        GLIS_ERROR_SWITCH_CASE_DEFAULT(name, err)
    }
    GLIS_INTERNAL_MESSAGE_PREFIX = "";
}

void GLIS_error_to_string_GL(GLint err) {
    GLIS_error_to_string_GL(nullptr, err);
}

void GLIS_error_to_string_EGL(EGLint err) {
    GLIS_error_to_string_EGL(nullptr, err);
}

void GLIS_error_to_string_GL() {
    GLIS_error_to_string_GL(glGetError());
}

void GLIS_error_to_string_EGL() {
    GLIS_error_to_string_EGL(eglGetError());
}

void GLIS_error_to_string() {
    GLIS_error_to_string_GL();
    GLIS_error_to_string_EGL();
}

void GLIS_error_to_string_GL(const char * name) {
    GLIS_error_to_string_GL(name, glGetError());
}

void GLIS_error_to_string_EGL(const char * name) {
    GLIS_error_to_string_EGL(name, eglGetError());
}

void GLIS_error_to_string(const char * name) {
    GLIS_error_to_string_GL(name);
    GLIS_error_to_string_EGL(name);
}

void GLIS_GL_INFORMATION() {
    const GLubyte * vendor = GLIS_error_to_string_exec_GL(glGetString(GL_VENDOR));
    const GLubyte * renderer = GLIS_error_to_string_exec_GL(glGetString(GL_RENDERER));
    const GLubyte * version = GLIS_error_to_string_exec_GL(glGetString(GL_VERSION));
    const GLubyte * slv = GLIS_error_to_string_exec_GL(glGetString(GL_SHADING_LANGUAGE_VERSION));
    const GLubyte * extentions = GLIS_error_to_string_exec_GL(glGetString(GL_EXTENSIONS));
    LOG_INFO("GL_VENDOR: %s", vendor);
    LOG_INFO("GL_RENDERER: %s", renderer);
    LOG_INFO("GL_VERSION: %s", version);
    LOG_INFO("GL_SHADING_LANGUAGE_VERSION: %s", slv);
    LOG_INFO("GL_EXTENSIONS: %s", extentions);
}

class GLIS_CLASS {
    public:
        int init_GLIS = false;
        bool
            init_eglGetDisplay = false,
            init_eglInitialize = false,
            init_eglChooseConfig = false,
            init_eglCreateWindowSurface = false,
            init_eglCreatePbufferSurface = false,
            init_eglCreateContext = false,
            init_eglMakeCurrent = false;
        const GLint
            * configuration_attributes = nullptr,
            * context_attributes = nullptr,
            * surface_attributes = nullptr;
        EGLint
            eglMajVers = 0,
            eglMinVers = 0,
            number_of_configurations = 0;
        EGLDisplay display = EGL_NO_DISPLAY;
        EGLConfig configuration = 0;
        EGLContext
            context = EGL_NO_CONTEXT,
            shared_context = EGL_NO_CONTEXT;
        EGLSurface surface = EGL_NO_SURFACE;
        ANativeWindow *native_window = nullptr;
        GLint
            width = 0,
            height = 0;
};

void GLIS_EGL_INFORMATION(EGLDisplay & DISPLAY) {
    const char * client_apis = GLIS_error_to_string_exec_EGL(eglQueryString(DISPLAY, EGL_CLIENT_APIS));
    const char * vendor = GLIS_error_to_string_exec_EGL(eglQueryString(DISPLAY, EGL_VENDOR));
    const char * version = GLIS_error_to_string_exec_EGL(eglQueryString(DISPLAY, EGL_VERSION));
    const char * extentions = GLIS_error_to_string_exec_EGL(eglQueryString(DISPLAY, EGL_EXTENSIONS));
    LOG_INFO("EGL_CLIENT_APIS: %s", client_apis);
    LOG_INFO("EGL_VENDOR: %s", vendor);
    LOG_INFO("EGL_VERSION: %s", version);
    LOG_INFO("EGL_EXTENSIONS: %s", extentions);
}

void GLIS_destroy_GLIS(class GLIS_CLASS & GLIS) {
    if (!GLIS.init_GLIS) return;

    if (GLIS.init_eglMakeCurrent) {
        GLIS_error_to_string_exec_EGL(eglMakeCurrent(GLIS.display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT));
        GLIS.init_eglMakeCurrent = false;
    }
    if(GLIS.init_eglCreateContext) {
        GLIS_error_to_string_exec_EGL(eglDestroyContext(GLIS.display, GLIS.context));
        GLIS.context = EGL_NO_CONTEXT;
        GLIS.shared_context = EGL_NO_CONTEXT;
        GLIS.init_eglCreateContext = false;
    }
    if (GLIS.init_eglCreateWindowSurface || GLIS.init_eglCreatePbufferSurface) {
        GLIS_error_to_string_exec_EGL(eglDestroySurface(GLIS.display, GLIS.surface));
        GLIS.surface = EGL_NO_SURFACE;
        GLIS.init_eglCreateWindowSurface = false;
        GLIS.init_eglCreatePbufferSurface = false;
    }
    if (GLIS.init_eglChooseConfig) {
        // TODO: figure how to undo init_eglChooseConfig
    }
    if (GLIS.init_eglInitialize) {
        GLIS_error_to_string_exec_EGL(eglTerminate(GLIS.display));
        GLIS.init_eglInitialize = false;
    }
    if (GLIS.init_eglGetDisplay) {
        GLIS.display = EGL_NO_DISPLAY;
        GLIS.init_eglGetDisplay = false;
    }
    GLIS.init_GLIS = false;
}


bool GLIS_initialize_display(class GLIS_CLASS & GLIS) {
    GLIS.display = GLIS_error_to_string_exec_EGL(eglGetDisplay(EGL_DEFAULT_DISPLAY));
    if (GLIS.display == EGL_NO_DISPLAY) return false;
    GLIS.init_eglGetDisplay = true;
    EGLBoolean r = GLIS_error_to_string_exec_EGL(eglInitialize(GLIS.display, &GLIS.eglMajVers, &GLIS.eglMinVers));
    if (r == EGL_FALSE) return false;
    GLIS.init_eglInitialize = true;
    LOG_INFO("EGL initialized with version %d.%d", GLIS.eglMajVers, GLIS.eglMinVers);
    GLIS_EGL_INFORMATION(GLIS.display);
    return true;
}

bool GLIS_initialize_configuration(class GLIS_CLASS & GLIS) {
    EGLBoolean r = GLIS_error_to_string_exec_EGL(eglChooseConfig(GLIS.display, GLIS.configuration_attributes, &GLIS.configuration, 1, &GLIS.number_of_configurations));
    if (r == EGL_FALSE) return false;
    GLIS.init_eglChooseConfig = true;
    return true;
}

bool GLIS_initialize_surface_CreateWindowSurface(class GLIS_CLASS & GLIS) {
    GLIS.surface = GLIS_error_to_string_exec_EGL(eglCreateWindowSurface(GLIS.display, GLIS.configuration, GLIS.native_window, nullptr));
    if (GLIS.surface == EGL_NO_SURFACE) return false;
    GLIS.init_eglCreateWindowSurface = true;
    return true;
}

bool GLIS_initialize_surface_CreatePbufferSurface(class GLIS_CLASS & GLIS) {
    GLIS.surface = GLIS_error_to_string_exec_EGL(eglCreatePbufferSurface(GLIS.display, GLIS.configuration, GLIS.surface_attributes));
    if (GLIS.surface == EGL_NO_SURFACE) return false;
    GLIS.init_eglCreatePbufferSurface = true;
    return true;
}

bool GLIS_create_context(class GLIS_CLASS & GLIS) {
    GLIS.context = GLIS_error_to_string_exec_EGL(eglCreateContext(GLIS.display, GLIS.configuration, GLIS.shared_context, GLIS.context_attributes));
    if (GLIS.context == EGL_NO_CONTEXT) return false;
    GLIS.init_eglCreateContext = true;
    return true;
}

bool GLIS_switch_to_context(class GLIS_CLASS & GLIS) {
    EGLBoolean r = GLIS_error_to_string_exec_EGL(eglMakeCurrent(GLIS.display, GLIS.surface, GLIS.surface, GLIS.context));
    if (r == EGL_FALSE) return false;
    GLIS.init_eglMakeCurrent = true;
    GLIS_GL_INFORMATION();
    return true;
}

bool GLIS_get_width_height(class GLIS_CLASS & GLIS) {
    EGLBoolean r1 = GLIS_error_to_string_exec_EGL(eglQuerySurface(GLIS.display, GLIS.surface, EGL_WIDTH, &GLIS.width));
    if (r1 == EGL_FALSE) return false;
    EGLBoolean r2 = GLIS_error_to_string_exec_EGL(eglQuerySurface(GLIS.display, GLIS.surface, EGL_HEIGHT, &GLIS.height));
    if (r2 == EGL_FALSE) return false;
    return true;
}

bool GLIS_initializeialize(class GLIS_CLASS & GLIS, GLint surface_type) {
    if (GLIS.init_GLIS) return true;

    LOG_INFO("Initializing");

    if ( eglBindAPI(EGL_OPENGL_ES_API) == EGL_FALSE) return false;
    
    LOG_INFO("Initializing display");
    if (!GLIS_initialize_display(GLIS)) {
        LOG_ERROR("Failed to initialize display");
        GLIS_destroy_GLIS(GLIS);
        return false;
    }
    LOG_INFO("Initialized display");
    LOG_INFO("Initializing configuration");
    if (!GLIS_initialize_configuration(GLIS)) {
        LOG_ERROR("Failed to initialize configuration");
        GLIS_destroy_GLIS(GLIS);
        return false;
    }
    LOG_INFO("Initialized configuration");
    LOG_INFO("Initializing surface");
    if (surface_type == EGL_WINDOW_BIT) {
        LOG_INFO("Creating window surface");
        if (!GLIS_initialize_surface_CreateWindowSurface(GLIS)) {
            LOG_ERROR("Failed to initialize surface");
            GLIS_destroy_GLIS(GLIS);
            return false;
        }
    }
    else if (surface_type == EGL_PBUFFER_BIT) {
        LOG_INFO("creating pixel buffer surface");
        if (!GLIS_initialize_surface_CreatePbufferSurface(GLIS)) {
            LOG_ERROR("Failed to initialize surface");
            GLIS_destroy_GLIS(GLIS);
            return false;
        }
    }
    LOG_INFO("Initialized surface");
    LOG_INFO("Initializing context");
    if (!GLIS_create_context(GLIS)) {
        LOG_ERROR("Failed to initialize context");
        GLIS_destroy_GLIS(GLIS);
        return false;
    }
    LOG_INFO("Initialized context");
    LOG_INFO("Switching to context");
    if (!GLIS_switch_to_context(GLIS)) {
        LOG_ERROR("Failed to switch to context");
        GLIS_destroy_GLIS(GLIS);
        return false;
    }
    LOG_INFO("Switched to context");
    LOG_INFO("Obtaining surface width and height");
    if (!GLIS_get_width_height(GLIS)) {
        LOG_ERROR("Failed to obtain surface width and height");
        GLIS_destroy_GLIS(GLIS);
        return false;
    }
    LOG_INFO("Obtained surface width and height");
    GLIS.init_GLIS = true;
    LOG_INFO("Initialized");
    return true;
}

bool GLIS_setupOnScreenRendering(class GLIS_CLASS & GLIS, EGLContext shared_context) {
    GLIS.shared_context = shared_context;

    const EGLint config[] = { EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT, EGL_NONE };
    GLIS.configuration_attributes = config;

    const EGLint context[] = { EGL_CONTEXT_CLIENT_VERSION, 3, EGL_NONE };
    GLIS.context_attributes = context;

    const EGLint surface[] = { EGL_RENDERABLE_TYPE, EGL_OPENGL_ES3_BIT, EGL_BLUE_SIZE, 8, EGL_GREEN_SIZE, 8, EGL_RED_SIZE, 8, EGL_ALPHA_SIZE, 8, EGL_DEPTH_SIZE, 16, EGL_NONE };
    GLIS.surface_attributes = surface;

    return GLIS_initializeialize(GLIS, EGL_WINDOW_BIT);
}

bool GLIS_setupOnScreenRendering(class GLIS_CLASS & GLIS) {
    return GLIS_setupOnScreenRendering(GLIS, EGL_NO_CONTEXT);
}

bool GLIS_setupOffScreenRendering(class GLIS_CLASS & GLIS, int w, int h, EGLContext shared_context) {
    GLIS.shared_context = shared_context;

    const EGLint config[] = { EGL_RENDERABLE_TYPE, EGL_OPENGL_ES3_BIT, EGL_NONE };
    GLIS.configuration_attributes = config;

    const EGLint context[] = { EGL_CONTEXT_CLIENT_VERSION, 3, EGL_NONE };
    GLIS.context_attributes = context;

    const EGLint surface[] = { EGL_WIDTH, w, EGL_HEIGHT, h, EGL_TEXTURE_FORMAT, EGL_TEXTURE_RGB, EGL_TEXTURE_TARGET, EGL_TEXTURE_2D, EGL_NONE };
    GLIS.surface_attributes = surface;

    return GLIS_initializeialize(GLIS, EGL_PBUFFER_BIT);
}

bool GLIS_setupOffScreenRendering(class GLIS_CLASS & GLIS, int w, int h) {
    return GLIS_setupOffScreenRendering(GLIS, w, h, EGL_NO_CONTEXT);
}

GLboolean GLIS_ShaderCompilerSupported() {
    GLboolean GLSC_supported;
    GLIS_error_to_string_exec_GL(glGetBooleanv(GL_SHADER_COMPILER, &GLSC_supported));
    LOG_INFO("Supports Shader Compiler: %s", GLSC_supported == GL_TRUE ? "true" : "false");
    return GLSC_supported;
}

GLuint GLIS_createShader(GLenum shaderType, const char * & src) {
    if (GLIS_ShaderCompilerSupported()) {
        const char * SHADER_TYPE = nullptr;
        switch (shaderType) {
            case GL_COMPUTE_SHADER:
                SHADER_TYPE = "Compute";
                break;
            case GL_FRAGMENT_SHADER:
                SHADER_TYPE = "Fragment";
                break;
            case GL_GEOMETRY_SHADER:
                SHADER_TYPE = "Geometry";
                break;
            case GL_VERTEX_SHADER:
                SHADER_TYPE = "Vertex";
                break;
            default:
                SHADER_TYPE = "Unknown";
                break;
        }
        LOG_INFO("Creating %s Shader", SHADER_TYPE);
        GLuint shader = GLIS_error_to_string_exec_GL(glCreateShader(shaderType));
        if (!shader) {
            return 0;
        }
        GLIS_error_to_string_exec_GL(glShaderSource(shader, 1, &src, nullptr));
        GLint compiled = GL_FALSE;
        LOG_INFO("Compiling %s Shader", SHADER_TYPE);
        GLIS_error_to_string_exec_GL(glCompileShader(shader));
        GLIS_error_to_string_exec_GL(glGetShaderiv(shader, GL_COMPILE_STATUS, &compiled));
        if (compiled != GL_TRUE) {
            GLint infoLogLen = 0;
            GLIS_error_to_string_exec_GL(glGetShaderiv(shader, GL_INFO_LOG_LENGTH, &infoLogLen));
            if (infoLogLen > 0) {
                GLchar *infoLog = (GLchar *) malloc(static_cast<size_t>(infoLogLen));
                if (infoLog) {
                    GLIS_error_to_string_exec_GL(
                            glGetShaderInfoLog(shader, infoLogLen, nullptr, infoLog));
                    LOG_ERROR("Could not compile %s shader:\n%s\n", SHADER_TYPE, infoLog);
                    free(infoLog);
                }
            }
            GLIS_error_to_string_exec_GL(glDeleteShader(shader));
            return 0;
        }
        assert(glIsShader(shader) == GL_TRUE);
        return shader;
    } else return 0;
}

GLboolean GLIS_validate_program_link(GLuint & Program) {
    GLint linked = GL_FALSE;
    GLIS_error_to_string_exec_GL(glGetProgramiv(Program, GL_LINK_STATUS, &linked));
    if (linked != GL_TRUE) {
        GLint infoLogLen = 0;
        GLIS_error_to_string_exec_GL(glGetProgramiv(Program, GL_INFO_LOG_LENGTH, &infoLogLen));
        if (infoLogLen > 0) {
            GLchar *infoLog = (GLchar *) malloc(static_cast<size_t>(infoLogLen));
            if (infoLog) {
                GLIS_error_to_string_exec_GL(
                        glGetProgramInfoLog(Program, infoLogLen, nullptr, infoLog));
                LOG_ERROR("Could not link program:\n%s\n", infoLog);
                free(infoLog);
            }
        }
        GLIS_error_to_string_exec_GL(glDeleteProgram(Program));
        return GL_FALSE;
    }
    return GL_TRUE;
}

GLboolean GLIS_validate_program_valid(GLuint & Program) {
    GLint validated = GL_FALSE;
    GLIS_error_to_string_exec_GL(glValidateProgram(Program));
    GLIS_error_to_string_exec_GL(glGetProgramiv(Program, GL_VALIDATE_STATUS, &validated));
    if (validated != GL_TRUE) {
        GLint infoLogLen = 0;
        GLIS_error_to_string_exec_GL(glGetProgramiv(Program, GL_INFO_LOG_LENGTH, &infoLogLen));
        if (infoLogLen > 0) {
            GLchar *infoLog = (GLchar *) malloc(static_cast<size_t>(infoLogLen));
            if (infoLog) {
                GLIS_error_to_string_exec_GL(
                        glGetProgramInfoLog(Program, infoLogLen, nullptr, infoLog));
                LOG_ERROR("Could not validate program:\n%s\n", infoLog);
                free(infoLog);
            }
        }
        GLIS_error_to_string_exec_GL(glDeleteProgram(Program));
        return GL_FALSE;
    }
    return GL_TRUE;
}

GLboolean GLIS_validate_program(GLuint & Program) {
    if (GLIS_validate_program_link(Program) == GL_TRUE)
        if (GLIS_validate_program_valid(Program) == GL_TRUE) {
            GLboolean v = GLIS_error_to_string_exec_GL(glIsProgram(Program));
            return v;
        }
    return GL_FALSE;
}

/*
// Normalized Device Coordinates (NDC)
                   height
( -1, 1)             | (  0,  1)  (  1,  1)
                     |
                     |
                     |
                     |
                     |
                     |
                     |
                     |
( -1,  0)            | (  0,  0)  (  1,  0)
---------------------+--------------------- width
                     |
                     |
                     |
                     |
                     |
                     |
                     |
                     |
                     |
( -1, -1)            | (  0, -1)   (  1, -1)

// height = 40
// width = 20

GLIS_set_conversion_origin(GLIS_CONVERSION_ORIGIN_TOP_LEFT);
GLIS_convertPair(0,0,20,40);
GLIS_convertPair(0,40,20,40);
GLIS_convertPair(20,0,20,40);
GLIS_convertPair(10,10,20,40);
GLIS_convertPair(10,20,20,40);
GLIS_convertPair(20,20,20,40);
GLIS_convertPair(20,40,20,40);
GLIS_set_conversion_origin(GLIS_CONVERSION_ORIGIN_TOP_RIGHT);
GLIS_convertPair(0,0,20,40);
GLIS_convertPair(0,40,20,40);
GLIS_convertPair(20,0,20,40);
GLIS_convertPair(10,10,20,40);
GLIS_convertPair(10,20,20,40);
GLIS_convertPair(20,20,20,40);
GLIS_convertPair(20,40,20,40);
GLIS_set_conversion_origin(GLIS_CONVERSION_ORIGIN_BOTTOM_LEFT);
GLIS_convertPair(0,0,20,40);
GLIS_convertPair(0,40,20,40);
GLIS_convertPair(20,0,20,40);
GLIS_convertPair(10,10,20,40);
GLIS_convertPair(10,20,20,40);
GLIS_convertPair(20,20,20,40);
GLIS_convertPair(20,40,20,40);
GLIS_set_conversion_origin(GLIS_CONVERSION_ORIGIN_BOTTOM_RIGHT);
GLIS_convertPair(0,0,20,40);
GLIS_convertPair(0,40,20,40);
GLIS_convertPair(20,0,20,40);
GLIS_convertPair(10,10,20,40);
GLIS_convertPair(10,20,20,40);
GLIS_convertPair(20,20,20,40);
GLIS_convertPair(20,40,20,40);

    converting with origin top left
    inverting 'y'
    width: 0, height: 0, ConvertPair: -1.000000, 1.000000
    inverting 'y'
    width: 0, height: 40, ConvertPair: -1.000000, -1.000000
    inverting 'y'
    width: 20, height: 0, ConvertPair: 1.000000, 1.000000
    inverting 'y'
    width: 10, height: 10, ConvertPair: 0.000000, 0.500000
    inverting 'y'
    width: 10, height: 20, ConvertPair: 0.000000, -0.000000
    inverting 'y'
    width: 20, height: 20, ConvertPair: 1.000000, -0.000000
    inverting 'y'
    width: 20, height: 40, ConvertPair: 1.000000, -1.000000
    converting with origin top right
    inverting 'x'
    inverting 'y'
    width: 0, height: 0, ConvertPair: 1.000000, 1.000000
    inverting 'x'
    inverting 'y'
    width: 0, height: 40, ConvertPair: 1.000000, -1.000000
    inverting 'x'
    inverting 'y'
    width: 20, height: 0, ConvertPair: -1.000000, 1.000000
    inverting 'x'
    inverting 'y'
    width: 10, height: 10, ConvertPair: -0.000000, 0.500000
    inverting 'x'
    inverting 'y'
    width: 10, height: 20, ConvertPair: -0.000000, -0.000000
    inverting 'x'
    inverting 'y'
    width: 20, height: 20, ConvertPair: -1.000000, -0.000000
    inverting 'x'
    inverting 'y'
    width: 20, height: 40, ConvertPair: -1.000000, -1.000000
    converting with origin bottom left
    no conversion
    width: 0, height: 0, ConvertPair: -1.000000, -1.000000
    no conversion
    width: 0, height: 40, ConvertPair: -1.000000, 1.000000
    no conversion
    width: 20, height: 0, ConvertPair: 1.000000, -1.000000
    no conversion
    width: 10, height: 10, ConvertPair: 0.000000, -0.500000
    no conversion
    width: 10, height: 20, ConvertPair: 0.000000, 0.000000
    no conversion
    width: 20, height: 20, ConvertPair: 1.000000, 0.000000
    no conversion
    width: 20, height: 40, ConvertPair: 1.000000, 1.000000
    converting with origin bottom right
    inverting 'x'
    width: 0, height: 0, ConvertPair: 1.000000, -1.000000
    inverting 'x'
    width: 0, height: 40, ConvertPair: 1.000000, 1.000000
    inverting 'x'
    width: 20, height: 0, ConvertPair: -1.000000, -1.000000
    inverting 'x'
    width: 10, height: 10, ConvertPair: -0.000000, -0.500000
    inverting 'x'
    width: 10, height: 20, ConvertPair: -0.000000, 0.000000
    inverting 'x'
    width: 20, height: 20, ConvertPair: -1.000000, 0.000000
    inverting 'x'
    width: 20, height: 40, ConvertPair: -1.000000, 1.000000
*/

template <typename TYPE>
float GLIS_inverse(TYPE num) {
    return num<0?-num:-(num);
}

template <typename TYPE>
float GLIS_convert(TYPE num, TYPE num_max) {
    // 3 year old magic
    return (num-(num_max/2))/(num_max/2);
}

template <typename TYPE>
class GLIS_coordinates {
    public:
        GLIS_coordinates(TYPE TYPE_INITIALIZER) {
            TYPE x = TYPE_INITIALIZER;
            TYPE y = TYPE_INITIALIZER;
        }

        TYPE x;
        TYPE y;
};

template <typename TYPE>
class GLIS_rect {
    public:
        GLIS_rect(TYPE TYPE_INITIALIZER) {
            topLeft = GLIS_coordinates<TYPE>(TYPE_INITIALIZER);
            topRight = GLIS_coordinates<TYPE>(TYPE_INITIALIZER);
            bottomLeft = GLIS_coordinates<TYPE>(TYPE_INITIALIZER);
            bottomRight = GLIS_coordinates<TYPE>(TYPE_INITIALIZER);
        }

        class GLIS_coordinates <TYPE> topLeft = NULL;
        class GLIS_coordinates <TYPE> topRight = NULL;
        class GLIS_coordinates <TYPE> bottomLeft = NULL;
        class GLIS_coordinates <TYPE> bottomRight = NULL;
};

template <typename TYPE>
class GLIS_rect<TYPE> GLIS_points_to_rect(TYPE TYPE_INITIALIZER, TYPE x1, TYPE y1, TYPE x2, TYPE y2) {
    class GLIS_rect<TYPE> r(TYPE_INITIALIZER);
    r.bottomLeft.x = x1;
    r.bottomLeft.y = y1;
    r.topRight.x = x2;
    r.topRight.y = y2;
    r.bottomRight.x = x2;
    r.bottomRight.y = y1;
    r.topLeft.x = x1;
    r.topLeft.y = y2;
    return r;
}

#define GLIS_CONVERSION_ORIGIN_TOP_LEFT 0
#define GLIS_CONVERSION_ORIGIN_TOP_RIGHT 1
#define GLIS_CONVERSION_ORIGIN_BOTTOM_LEFT 2
#define GLIS_CONVERSION_ORIGIN_BOTTOM_RIGHT 3

int GLIS_CONVERSION_ORIGIN = GLIS_CONVERSION_ORIGIN_BOTTOM_LEFT;

void GLIS_set_conversion_origin(int origin) {
    GLIS_CONVERSION_ORIGIN = origin;
    switch (GLIS_CONVERSION_ORIGIN) {
        case GLIS_CONVERSION_ORIGIN_TOP_LEFT:
            LOG_INFO("converting with origin top left");
            break;
        case GLIS_CONVERSION_ORIGIN_TOP_RIGHT:
            LOG_INFO("converting with origin top right");
            break;
        case GLIS_CONVERSION_ORIGIN_BOTTOM_LEFT:
            LOG_INFO("converting with origin bottom left");
            break;
        case GLIS_CONVERSION_ORIGIN_BOTTOM_RIGHT:
            LOG_INFO("converting with origin bottom right");
            break;
        default:
            LOG_INFO("unknown conversion");
            break;
    }
}

template <typename TYPEFROM, typename TYPETO>
class GLIS_coordinates<TYPETO> GLIS_convertPair(TYPETO TYPETO_INITIALIZER, TYPEFROM x, TYPEFROM y, TYPEFROM x_max, TYPEFROM y_max, bool clip) {
    class GLIS_coordinates<TYPETO> xy(TYPETO_INITIALIZER);
    if (x > x_max) {
        LOG_INFO("x is out of bounds (expected %hi, got %hi)", x_max, x);
        if (clip) {
            LOG_INFO("clipping to %hi", x_max);
            x = x_max;
        }
    }
    else if (x < 0) {
        LOG_INFO("x is out of bounds (expected %hi, got %hi)\n", 0, x);
        if (clip) {
            LOG_INFO("clipping to %hi", 0);
            x = 0;
        }
    }
    if (y > y_max) {
        LOG_INFO("y is out of bounds (expected %hi, got %hi)\n", y_max, y);
        if (clip) {
            LOG_INFO("clipping to %hi", y_max);
            y = y_max;
        }
    }
    else if (y < 0) {
        LOG_INFO("y is out of bounds (expected %hi, got %hi)\n", 0, y);
        if (clip) {
            LOG_INFO("clipping to %hi", 0);
            y = 0;
        }
    }
    xy.x = GLIS_convert<TYPETO>(static_cast<TYPETO>(x), static_cast<TYPETO>(x_max)); // x
    xy.y = GLIS_convert<TYPETO>(static_cast<TYPETO>(y), static_cast<TYPETO>(y_max)); // y
    switch (GLIS_CONVERSION_ORIGIN) {
        case GLIS_CONVERSION_ORIGIN_TOP_LEFT:
            LOG_INFO("inverting 'y'");
            xy.y = GLIS_inverse<TYPETO>(xy.y);
            break;
        case GLIS_CONVERSION_ORIGIN_TOP_RIGHT:
            LOG_INFO("inverting 'x'");
            xy.x = GLIS_inverse<TYPETO>(xy.x);
            LOG_INFO("inverting 'y'");
            xy.y = GLIS_inverse<TYPETO>(xy.y);
            break;
        case GLIS_CONVERSION_ORIGIN_BOTTOM_LEFT: {
            LOG_INFO("no conversion");
            break;
        }
        case GLIS_CONVERSION_ORIGIN_BOTTOM_RIGHT:
            LOG_INFO("inverting 'x'");
            xy.x = GLIS_inverse<TYPETO>(xy.x);
            break;
        default:
            LOG_INFO("unknown conversion");
            break;
    }
    LOG_INFO("width: %hi, width_max: %hi, height: %hi, height_max: %hi, ConvertPair: %f, %f\n", x, x_max, y, y_max, xy.x, xy.y);
    return xy;
}

template <typename TYPEFROM, typename TYPETO>
class GLIS_coordinates<TYPETO> GLIS_convertPair(TYPETO TYPETO_INITIALIZER, TYPEFROM x, TYPEFROM y, TYPEFROM x_max, TYPEFROM y_max) {
    return GLIS_convertPair<TYPEFROM, TYPETO>(TYPETO_INITIALIZER, x, y, x_max, y_max, true);
}

template <typename TYPE>
struct GLIS_quater_position {
    TYPE x;
    TYPE y;
    TYPE z;
};

template <typename TYPE>
struct GLIS_quater_color {
    TYPE R;
    TYPE G;
    TYPE B;
};

template <typename TYPE>
struct GLIS_quater {
    struct GLIS_quater_position<TYPE> position;
    struct GLIS_quater_color<TYPE> color;
    struct GLIS_quater_position<TYPE> texture_position;
};

template <typename TYPE>
struct GLIS_vertex_map_rectangle {
    struct GLIS_quater<TYPE> top_right;
    struct GLIS_quater<TYPE> bottom_right;
    struct GLIS_quater<TYPE> bottom_left;
    struct GLIS_quater<TYPE> top_left;
};

template <typename TYPE>
class GLIS_vertex_data {
    public:
        TYPE *vertex;
        int size_of_position;
        int size_of_color;
        int size_of_texture_position;
        int size_per_quater;
        int number_of_points;
        size_t vertex_size;
        unsigned int *indices;
        size_t indices_size;
        size_t typesize;

        void print(const char *format) {
            std::string fmt = "\n";
            fmt += "VECTOR OUTPUT:    |       positions       |       colors          |texture positions|";
            fmt += "\n";
            fmt += "VALUES:           |   X      Y      Z     |   R      B      G     |   X      Y      |";
            fmt += "\n";
            fmt += "TOP RIGHT:      ";
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format;
            fmt += "   |";
            fmt += "\n";
            fmt += "BOTTOM RIGHT:   ";
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format;
            fmt += "   |";
            fmt += "\n";
            fmt += "BOTTOM LEFT:    ";
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format;
            fmt += "   |";
            fmt += "\n";
            fmt += "TOP LEFT:       ";
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format; fmt += ", "; fmt += format;
            fmt += "  |  ";
            fmt += format; fmt += ", "; fmt += format;
            fmt += "   |";
            LOG_INFO(fmt.c_str(),
                     vertex[0], vertex[1], vertex[2],
                     vertex[3], vertex[4], vertex[5],
                     vertex[6], vertex[7],
                     vertex[8], vertex[9], vertex[10],
                     vertex[11], vertex[12], vertex[13],
                     vertex[14], vertex[15],
                     vertex[16], vertex[17], vertex[18],
                     vertex[19], vertex[20], vertex[21],
                     vertex[22], vertex[23],
                     vertex[24], vertex[25], vertex[26],
                     vertex[27], vertex[28], vertex[29],
                     vertex[30], vertex[31]
            );
        }

        void init_attributes() {
            // position attribute
            GLIS_error_to_string_exec_GL(glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 8 * sizeof(float), (void*)0));
            GLIS_error_to_string_exec_GL(glEnableVertexAttribArray(0));
            // color attribute
            GLIS_error_to_string_exec_GL(glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 8 * sizeof(float), (void*)(3 * sizeof(float))));
            GLIS_error_to_string_exec_GL(glEnableVertexAttribArray(1));
            // texture coord attribute
            GLIS_error_to_string_exec_GL(glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, 8 * sizeof(float), (void*)(6 * sizeof(float))));
            GLIS_error_to_string_exec_GL(glEnableVertexAttribArray(2));
        }
};

template <typename TYPE>
void GLIS_fill_vertex_rect(TYPE * vertex, struct GLIS_quater<TYPE> & quater, int offset) {
    vertex[offset+0] = quater.position.x;
    vertex[offset+1] = quater.position.y;
    vertex[offset+2] = quater.position.z;
    vertex[offset+3] = quater.color.R;
    vertex[offset+4] = quater.color.G;
    vertex[offset+5] = quater.color.B;
    vertex[offset+6] = quater.texture_position.x;
    vertex[offset+7] = quater.texture_position.y;
};

template <typename TYPE>
struct GLIS_vertex_data<TYPE> GLIS_build_vertex_rect(struct GLIS_vertex_map_rectangle<TYPE> & data) {
    struct GLIS_vertex_data<TYPE> v;
    v.typesize = sizeof(TYPE);
    v.size_of_position = 3;
    v.size_of_color = 3;
    v.size_of_texture_position = 2;
    v.size_per_quater = v.size_of_position+v.size_of_color+v.size_of_texture_position;
    v.number_of_points = 4;
    v.vertex_size = v.typesize*(v.size_per_quater*v.number_of_points);
    v.vertex = static_cast<TYPE*>(malloc(v.vertex_size));
    GLIS_fill_vertex_rect(v.vertex, data.top_right, 0*v.size_per_quater);
    GLIS_fill_vertex_rect(v.vertex, data.bottom_right, 1*v.size_per_quater);
    GLIS_fill_vertex_rect(v.vertex, data.bottom_left, 2*v.size_per_quater);
    GLIS_fill_vertex_rect(v.vertex, data.top_left, 3*v.size_per_quater);
    v.indices_size = 6 * sizeof(unsigned int);
    v.indices = static_cast<unsigned int *>(malloc(v.indices_size));
    v.indices[0] = 0;
    v.indices[1] = 1;
    v.indices[2] = 3;
    v.indices[3] = 1;
    v.indices[4] = 2;
    v.indices[5] = 3;
    return v;
}

template <typename TYPEFROM, typename TYPETO>
struct GLIS_vertex_map_rectangle<TYPETO> GLIS_build_vertex_data_rect(TYPETO TYPETO_INITIALIZER, class GLIS_rect<TYPEFROM> data, TYPEFROM max_x, TYPEFROM max_y) {
    struct GLIS_vertex_map_rectangle<TYPETO> m;
    GLIS_coordinates<TYPETO> point1 = GLIS_convertPair<TYPEFROM, TYPETO>(TYPETO_INITIALIZER, data.topLeft.x,data.topLeft.y,max_x,max_y);
    m.top_left.position.x = point1.x;
    m.top_left.position.y = point1.y;
    m.top_left.position.z = 0.0F;
    m.top_left.texture_position.x = 0.0F;
    m.top_left.texture_position.y = 1.0F;
    m.top_left.texture_position.z = 0.0F;
    m.top_left.color.R = 1.0F;
    m.top_left.color.G = 1.0F;
    m.top_left.color.B = 1.0F;
    GLIS_coordinates<TYPETO> point2 = GLIS_convertPair<TYPEFROM, TYPETO>(TYPETO_INITIALIZER, data.topRight.x,data.topRight.y,max_x,max_y);
    m.top_right.position.x = point2.x;
    m.top_right.position.y = point2.y;
    m.top_right.position.z = 0.0F;
    m.top_right.texture_position.x = 1.0F;
    m.top_right.texture_position.y = 1.0F;
    m.top_right.texture_position.z = 0.0F;
    m.top_right.color.R = 0.0F;
    m.top_right.color.G = 1.0F;
    m.top_right.color.B = 0.0F;
    GLIS_coordinates<TYPETO> point3 = GLIS_convertPair<TYPEFROM, TYPETO>(TYPETO_INITIALIZER, data.bottomLeft.x,data.bottomLeft.y,max_x,max_y);
    m.bottom_left.position.x = point3.x;
    m.bottom_left.position.y = point3.y;
    m.bottom_left.position.z = 0.0F;
    m.bottom_left.texture_position.x = 0.0F;
    m.bottom_left.texture_position.y = 0.0F;
    m.bottom_left.texture_position.z = 0.0F;
    m.bottom_left.color.R = 1.0F;
    m.bottom_left.color.G = 0.0F;
    m.bottom_left.color.B = 0.0F;
    GLIS_coordinates<TYPETO> point4 = GLIS_convertPair<TYPEFROM, TYPETO>(TYPETO_INITIALIZER, data.bottomRight.x,data.bottomRight.y,max_x,max_y);
    m.bottom_right.position.x = point4.x;
    m.bottom_right.position.y = point4.y;
    m.bottom_right.position.z = 0.0F;
    m.bottom_right.texture_position.x = 1.0F;
    m.bottom_right.texture_position.y = 0.0F;
    m.bottom_right.texture_position.z = 0.0F;
    m.bottom_right.color.R = 0.0F;
    m.bottom_right.color.G = 0.0F;
    m.bottom_right.color.B = 1.0F;
    return m;
}

template <typename TYPE>
void GLIS_draw_rectangle(TYPE INITIALIZER, TYPE x1, TYPE y1, TYPE x2, TYPE y2, TYPE max_x, TYPE max_y) {
    class GLIS_rect<GLint> r = GLIS_points_to_rect<GLint>(INITIALIZER, x1, y1, x2, y2);
    struct GLIS_vertex_map_rectangle<float> vmr = GLIS_build_vertex_data_rect<GLint, float>(0.0F, r, max_x, max_y);
    class GLIS_vertex_data<float> v = GLIS_build_vertex_rect<float>(vmr);
    v.print("%4.1ff");

    GLuint vertex_array_object;
    GLuint vertex_buffer_object;
    GLuint element_buffer_object;
    LOG_INFO("Generating buffers");
    GLIS_error_to_string_exec_GL(glGenVertexArrays(1, &vertex_array_object));
    GLIS_error_to_string_exec_GL(glGenBuffers(1, &vertex_buffer_object));
    GLIS_error_to_string_exec_GL(glGenBuffers(1, &element_buffer_object));
    LOG_INFO("Binding buffers");
    GLIS_error_to_string_exec_GL(glBindVertexArray(vertex_array_object));
    GLIS_error_to_string_exec_GL(glBindBuffer(GL_ARRAY_BUFFER, vertex_buffer_object));
    GLIS_error_to_string_exec_GL(glBufferData(GL_ARRAY_BUFFER, v.vertex_size, v.vertex, GL_STATIC_DRAW));
    GLIS_error_to_string_exec_GL(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, element_buffer_object));
    GLIS_error_to_string_exec_GL(glBufferData(GL_ELEMENT_ARRAY_BUFFER, v.indices_size, v.indices, GL_STATIC_DRAW));
    LOG_INFO("Initializing Attributes");
    v.init_attributes();

    LOG_INFO("Drawing rectangle");
    GLIS_error_to_string_exec_GL(glBindVertexArray(vertex_array_object));
    GLIS_error_to_string_exec_GL(glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_INT, nullptr));
    GLIS_error_to_string_exec_GL(glBindVertexArray(0));
    GLIS_error_to_string_exec_GL(glBindBuffer(GL_ARRAY_BUFFER, 0));
    GLIS_error_to_string_exec_GL(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
    GLIS_error_to_string_exec_GL(glDeleteVertexArrays(1, &vertex_array_object));
    GLIS_error_to_string_exec_GL(glDeleteBuffers(1,&vertex_buffer_object));
    GLIS_error_to_string_exec_GL(glDeleteBuffers(1, &element_buffer_object));
}

void GLIS_set_texture(GLenum textureUnit, GLuint texture) {
    GLIS_error_to_string_exec_GL(glActiveTexture(textureUnit));
    GLIS_error_to_string_exec_GL(glBindTexture(GL_TEXTURE_2D, texture));
}

template <typename TYPE>
void GLIS_draw_rectangle(GLenum textureUnit, GLuint texture, TYPE INITIALIZER, TYPE x1, TYPE y1, TYPE x2, TYPE y2, TYPE max_x, TYPE max_y) {
    GLIS_set_texture(textureUnit, texture);
    GLIS_draw_rectangle<TYPE>(INITIALIZER, x1, y1, x2, y2, max_x, max_y);
}

void GLIS_texture_buffer(GLuint & framebuffer, GLuint & renderbuffer, GLuint & renderedTexture, GLint & texture_width, GLint & texture_height) {
    GLIS_error_to_string_exec_GL(glGenFramebuffers(1, &framebuffer));
    GLIS_error_to_string_exec_GL(glBindFramebuffer(GL_FRAMEBUFFER, framebuffer));
    GLIS_error_to_string_exec_GL(glGenRenderbuffers(1, &renderbuffer));
    GLIS_error_to_string_exec_GL(glBindRenderbuffer(GL_RENDERBUFFER, renderbuffer));
    GLIS_error_to_string_exec_GL(glRenderbufferStorage(GL_RENDERBUFFER, GL_RGBA8UI, texture_width, texture_height));
    GLIS_error_to_string_exec_GL(glFramebufferRenderbuffer(GL_FRAMEBUFFER,
                                                        GL_COLOR_ATTACHMENT0,
                                                        GL_RENDERBUFFER,
                                                        renderbuffer));
    GLIS_error_to_string_exec_GL(glBindFramebuffer(GL_FRAMEBUFFER, framebuffer));

    GLenum FramebufferStatus = GLIS_error_to_string_exec_GL(
        glCheckFramebufferStatus(GL_FRAMEBUFFER));

    if (FramebufferStatus != GL_FRAMEBUFFER_COMPLETE)
        LOG_ERROR("framebuffer is not complete");
    else
        LOG_INFO("framebuffer is complete");

    // create a new texture
    GLIS_error_to_string_exec_GL(glGenTextures(1, &renderedTexture));
    GLIS_error_to_string_exec_GL(glBindTexture(GL_TEXTURE_2D, renderedTexture));
    GLIS_error_to_string_exec_GL(glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, texture_width, texture_height, 0, GL_RGBA, GL_UNSIGNED_BYTE,0));
    GLIS_error_to_string_exec_GL(glGenerateMipmap(GL_TEXTURE_2D));
    GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));
    GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
    GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER));
    GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER));
    // Set "renderedTexture" as our colour attachement #0
    GLIS_error_to_string_exec_GL(glFramebufferTexture(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, renderedTexture, 0));
    // Set the list of draw buffers.
    GLenum DrawBuffers[1] = {GL_COLOR_ATTACHMENT0};
    GLIS_error_to_string_exec_GL(glDrawBuffers(1, DrawBuffers)); // "1" is the size of DrawBuffers
}

GLuint GLIS_current_texture = 0;

void GLIS_Sync_GPU() {
    LOG_INFO("synchronizing with GPU");
    GLsync GPU = GLIS_error_to_string_exec_GL(glFenceSync(GL_SYNC_GPU_COMMANDS_COMPLETE, 0));
    if (GPU == nullptr) LOG_ERROR("glFenceSync failed at workingFunction.");
    LOG_INFO("synchronizing");
    GLIS_error_to_string_exec(glWaitSync(GPU, 0, GL_TIMEOUT_IGNORED));
    LOG_INFO("synchronized");
    glDeleteSync(GPU);
    LOG_INFO("synchronized with GPU");
}

class STATE {
    public:
        int no_state = 0;
        int request_startup = 1;
        int response_starting_up = 2;
        int response_started_up = 3;
        int request_shutdown = 4;
        int response_shutting_down = 5;
        int response_shutdown = 6;
        int request_upload = 7;
        int response_uploading = 8;
        int response_uploaded = 9;
        int request_render = 10;
        int response_rendering = 11;
        int response_rendered = 12;
} STATE;

int SYNC_STATE = STATE.no_state;

class IPC_MODE {
    public:
        int thread = 0;
        int texture = 1;
        int socket = 2;
} IPC_MODE;

int IPC = IPC_MODE.socket;

class SOCKET_SERVER_DATA {
    public:
        bool server_CAN_CONNECT = false;
        bool server_should_close = false;
        bool server_should_close_during_accept = false;
        bool server_closed = false;
        struct sockaddr_un server_addr = {0};
        char socket_name[108] = {0}; // 108 sun_path length max
};

void SERVER_SHUTDOWN(SOCKET_SERVER_DATA * internaldata) {
    if (!internaldata->server_closed) return;
    internaldata->server_should_close = true;
    while (!internaldata->server_closed);
}

void* SERVER_START(void* na) {
    assert(na != nullptr);
    SOCKET_SERVER_DATA * internaldata = static_cast<SOCKET_SERVER_DATA*>(na);
    ssize_t ret;
    int buffer;
    int socket_fd;
    int data_socket;
    bool has_data_socket = false;

    LOG_INFO("SERVER: Start server setup: %s", internaldata->socket_name+1);

    // AF_UNIX for domain unix IPC and SOCK_STREAM since it works for the example
    socket_fd = socket(AF_UNIX, SOCK_STREAM|SOCK_NONBLOCK, 0);
    if (socket_fd < 0) {
        LOG_ERROR("SERVER: socket: %s", strerror(errno));
        exit(EXIT_FAILURE);
    }
    LOG_INFO("SERVER: Socket made");

    // clear for safty
    memset(&internaldata->server_addr, 0, sizeof(struct sockaddr_un));
    internaldata->server_addr.sun_family = AF_UNIX; // Unix Domain instead of AF_INET IP domain
    memcpy(internaldata->server_addr.sun_path, internaldata->socket_name, 108);
    LOG_INFO("SERVER: binding socket fd %d to name %s", socket_fd, internaldata->server_addr.sun_path +1);
    ret = bind(socket_fd, (const struct sockaddr *) &internaldata->server_addr, sizeof(struct sockaddr_un));
    if (ret < 0) {
        LOG_ERROR("SERVER: bind: %s", strerror(errno));
        exit(EXIT_FAILURE);
    }
    LOG_INFO("SERVER: Bind made");

    // Open 8 back buffers for this demo
    ret = listen(socket_fd, 8);
    if (ret < 0) {
        LOG_ERROR("SERVER: listen: %s", strerror(errno));
        exit(EXIT_FAILURE);
    }
    LOG_INFO("SERVER: Socket listening for packages");
    internaldata->server_CAN_CONNECT = true;
    LOG_INFO("SERVER: Server setup complete: server name: %s", internaldata->socket_name+1);

    while (!internaldata->server_should_close) {
        // Wait for incoming connection.
        has_data_socket = false;
        for(;;) {
            if (internaldata->server_should_close) {
                internaldata->server_should_close_during_accept = true;
                break;
            }
            data_socket = accept(socket_fd, NULL, NULL);
            if (data_socket < 0) {
                if (errno == EAGAIN || errno == EWOULDBLOCK) continue;
                else break;
            }
            break;
        }
        if (internaldata->server_should_close_during_accept) continue;
        if (data_socket < 0) {
            LOG_ERROR("SERVER: accept: %s", strerror(errno));
            SERVER_SHUTDOWN(internaldata);
            exit(EXIT_FAILURE);
        }
        has_data_socket = true;
        LOG_INFO("SERVER: %s : Accepted data", internaldata->server_addr.sun_path + 1);
        // This is the main loop for handling connections
        struct pollfd pfd;
        pfd.fd = data_socket;
        pfd.events = POLLIN | POLLHUP | POLLRDNORM;
        pfd.revents = 0;
        // Wait for next data packet
        // call poll with a timeout of 100 ms
        if (poll(&pfd, 1, 100) > 0) { // if data_socket has data
            // CHECK IF DATA IS VALID
            // if result > 0, this means that there is either data available on the
            // socket, or the socket has been closed
            for(;;) {
                ret = recv(data_socket, &buffer, sizeof(int), MSG_PEEK | MSG_DONTWAIT);
                if (ret < 0) {
                    if (errno == EAGAIN || errno == EWOULDBLOCK) continue;
                    else break;
                }
                break;
            }
            if (ret == 0) {
                // if recv returns zero, that means the connection has been closed
                LOG_INFO("SERVER: %s : Client has closed the connection",
                         internaldata->server_addr.sun_path + 1);
                continue;
            } else if (ret < 0) {
                LOG_ERROR("SERVER: %s : recv: %s", internaldata->server_addr.sun_path + 1,
                          strerror(errno));
                continue;
            }
            // DATA IS VALID
            for(;;) {
                ret = recv(data_socket, &buffer, sizeof(int), NULL);
                if (ret < 0) {
                    if (errno == EAGAIN || errno == EWOULDBLOCK) continue;
                    else break;
                }
                break;
            }
            if (ret < 0) {
                LOG_ERROR("SERVER: %s : recv: %s", internaldata->server_addr.sun_path + 1,
                          strerror(errno));
                continue;
            }
            LOG_INFO("SERVER: %s : Buffer: %d", internaldata->server_addr.sun_path + 1, buffer);
            // Send back result
            buffer = false;
            for(;;) {
                ret = write(data_socket, &buffer, sizeof(int));
                if (ret < 0) {
                    if (errno == EAGAIN || errno == EWOULDBLOCK) continue;
                    else break;
                }
                break;
            }
            if (ret < 0) {
                LOG_ERROR("SERVER: %s : write: %s", internaldata->server_addr.sun_path + 1,
                          strerror(errno));
                continue;
            }
            LOG_INFO("SERVER: %s : Return: %d", internaldata->server_addr.sun_path + 1, buffer);
        }
    }
    LOG_INFO("SERVER: closing server: %s", internaldata->server_addr.sun_path+1);
    if (has_data_socket) close(data_socket);
    close(socket_fd);
    internaldata->server_closed = true;
    LOG_INFO("SERVER: closed server: %s", internaldata->server_addr.sun_path+1);
    return NULL;
}

class SOCKET_SERVER {
    private:
        pthread_t server_thread = 0;
        char server_name[107];
        const char * default_server_name = "SOCKET_SERVER";
        const size_t default_server_name_length = strlen(default_server_name);
        SOCKET_SERVER_DATA * internaldata = nullptr;
    public:
        void startServer() {
            if (internaldata != nullptr) return;
            internaldata = new SOCKET_SERVER_DATA;
            internaldata->server_CAN_CONNECT = false;
            internaldata->server_should_close = false;
            internaldata->server_closed = false;
            memset(internaldata->socket_name, 0, 108);
            // NDK needs abstract namespace by leading with '\0'
            internaldata->socket_name[0] = '\0';
            if (strlen(server_name) > 107) {
                LOG_ERROR("SERVER: name is longer than 107 characters, truncating, conflicts may happen");
                memcpy(&internaldata->socket_name[1], server_name, 107);
            } else memcpy(&internaldata->socket_name[1], server_name, strlen(server_name));
            pthread_create(&server_thread, NULL, SERVER_START, internaldata);
            while(!internaldata->server_CAN_CONNECT) {}
        }
        void shutdownServer() {
            if (internaldata == nullptr) return;
            if (!internaldata->server_closed) SERVER_SHUTDOWN(internaldata);
            delete internaldata;
        }
        SOCKET_SERVER(const char * name) {
            memset(&server_name, 0, 107);
            if (name == nullptr || name == NULL) {
                LOG_ERROR("SERVER: name was not supplied, conflicts are likely to happen");
                if (strlen(default_server_name) > 107) {
                    LOG_ERROR("SERVER: default name is longer than 107 characters, truncating");
                    memcpy(server_name, default_server_name, 107);
                } else memcpy(server_name, default_server_name, default_server_name_length);
            }
            else if (strlen(server_name) > 107) {
                LOG_ERROR("SERVER: name is longer than 107 characters, truncating, conflicts may happen");
                memcpy(server_name, name, 107);
            } else memcpy(server_name, name, strlen(name));
            startServer();
        }
        ~SOCKET_SERVER() {
            shutdownServer();
        }
};

class SOCKET_CLIENT {
    public:
        const size_t BUFFER_SIZE = 16;

        int data_socket;
        struct sockaddr_un server_addr;

        SOCKET_CLIENT(const char * name) {
            char socket_name[108]; // 108 sun_path length max
            memset(&socket_name, 0, 108);
            if (name == nullptr || name == NULL) name = const_cast<char *>("SOCKET_SERVER");
            socket_name[0] = '\0';
            if (strlen(name) > 107) {
                LOG_ERROR("CLIENT: name is longer than 107, conflicts may happen");
                memcpy(&socket_name[1], name, 107);
            } else memcpy(&socket_name[1], name, strlen(name));
            // clear for safty
            memset(&server_addr, 0, sizeof(struct sockaddr_un));
            server_addr.sun_family = AF_UNIX; // Unix Domain instead of AF_INET IP domain
            memcpy(server_addr.sun_path, socket_name, 108);
        }
        void sendTRUE(void) {
            data_socket = socket(AF_UNIX, SOCK_STREAM, 0);
            if (data_socket < 0) {
                LOG_ERROR("CLIENT: socket: %s", strerror(errno));
                exit(EXIT_FAILURE);
            }
            LOG_INFO("CLIENT: connecting to server: %s", server_addr.sun_path+1);
            ssize_t ret = connect(data_socket, (const struct sockaddr *) &server_addr, sizeof(struct sockaddr_un));
            if (ret < 0) {
                LOG_ERROR("CLIENT: connect: %s", strerror(errno));
                exit(EXIT_FAILURE);
            }
            LOG_INFO("CLIENT: connected to server: %s", server_addr.sun_path+1);
            int data = true;

            LOG_INFO("CLIENT: %s : writing Data: %d", server_addr.sun_path+1, data);

            ret = write(data_socket, &data, sizeof(data));
            if (ret < 0) {
                LOG_ERROR("CLIENT: %s : write: %s", server_addr.sun_path+1, strerror(errno));
                exit(EXIT_FAILURE);
            }
            LOG_INFO("CLIENT: %s : wrote Data: %d", server_addr.sun_path+1, data);

            LOG_INFO("CLIENT: %s : reading", server_addr.sun_path+1);

            ret = read(data_socket, &data, sizeof(data));
            if (ret < 0) {
                LOG_ERROR("CLIENT: %s : read: %s", server_addr.sun_path+1, strerror(errno));
                exit(EXIT_FAILURE);
            }

            LOG_INFO("CLIENT: %s : Return: %d", server_addr.sun_path+1, data);
            LOG_INFO("CLIENT: closing connection to server: %s", server_addr.sun_path+1);
            close(data_socket);
            LOG_INFO("CLIENT: closed connection to server: %s", server_addr.sun_path+1);
        }
};

GLuint *TEXDATA = nullptr;
size_t TEXDATA_LEN = 0;

void GLIS_upload_texture(GLuint & TEXTURE, GLint texture_width, GLint texture_height) {
    while (SYNC_STATE != STATE.request_upload) {}
    LOG_INFO("uploading texture");
    GLIS_Sync_GPU();
    SYNC_STATE = STATE.response_uploading;
    if (IPC == IPC_MODE.thread) {
        GLIS_current_texture = TEXTURE;
    } else if (IPC == IPC_MODE.texture) {
        TEXDATA_LEN = texture_width * texture_height * sizeof(GLuint);
        TEXDATA = new GLuint[TEXDATA_LEN];
        GLIS_error_to_string_exec_GL(glReadPixels(0, 0, texture_width, texture_height, GL_RGBA, GL_UNSIGNED_BYTE, TEXDATA));
    } else if (IPC == IPC_MODE.socket) {
        TEXDATA_LEN = texture_width * texture_height * sizeof(GLuint);
        TEXDATA = new GLuint[TEXDATA_LEN];
        GLIS_error_to_string_exec_GL(glReadPixels(0, 0, texture_width, texture_height, GL_RGBA, GL_UNSIGNED_BYTE, TEXDATA));
        SOCKET_SERVER serverA("A");
        SOCKET_SERVER serverB("B");
        SOCKET_CLIENT clientA("A");
        SOCKET_CLIENT clientB("B");
        serverA.startServer();
        serverB.startServer();
        serverA.startServer();
        serverB.startServer();
        clientA.sendTRUE();
        clientA.sendTRUE();
        clientB.sendTRUE();
        clientB.sendTRUE();
        serverA.shutdownServer();
        serverB.shutdownServer();
        serverA.shutdownServer();
        serverB.shutdownServer();
        exit(55);
//LOG_INFO("new socket");
//X2 = GLIS_new_socket("Compositor");
//assert(X2 != nullptr);
//LOG_INFO("created new socket");
//LOG_INFO("bind socket");
//assert(X2->bindToSocket());
//LOG_INFO("binded to socket");
//LOG_INFO("listen socket");
//assert(X2->listenToSocket());
//LOG_INFO("listening to socket");
//LOG_INFO("new socket");
//X1 = GLIS_new_socket("Compositor");
//assert(X1 != nullptr);
//LOG_INFO("created new socket");
//LOG_INFO("connect socket");
//assert(X1->connectToSocket());
//LOG_INFO("connected to socket");
//LOG_INFO("accept socket");
//assert(X2->acceptFromSocket());
//LOG_INFO("accepted socket");
//LOG_INFO("send socket");
//assert(X1->send(TEXDATA, TEXDATA_LEN));
//LOG_INFO("sent socket");
//LOG_INFO("receive socket");
//assert(X2->receive(TEXDATA, TEXDATA_LEN));
//LOG_INFO("received socket");
        delete TEXDATA;
    }
    SYNC_STATE = STATE.response_uploaded;
    LOG_INFO("uploaded texture");
    LOG_INFO("requesting SERVER to render");
    SYNC_STATE = STATE.request_render;
    while (SYNC_STATE != STATE.response_rendered) {}
    LOG_INFO("SERVER has rendered");
}

void GLIS_get_texture(GLuint & TEXTURE, GLint texture_width, GLint texture_height) {
    LOG_INFO("acquiring uploaded texture");
    GLIS_Sync_GPU();
    if (IPC == IPC_MODE.thread) {
        GLIS_current_texture = TEXTURE;
    } else if (IPC == IPC_MODE.texture) {
        GLIS_error_to_string_exec_GL(glGenTextures(1, &GLIS_current_texture));
        GLIS_error_to_string_exec_GL(glBindTexture(GL_TEXTURE_2D, GLIS_current_texture));
        GLIS_error_to_string_exec_GL(glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, texture_width, texture_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, TEXDATA));
        delete TEXDATA;
        GLIS_error_to_string_exec_GL(glGenerateMipmap(GL_TEXTURE_2D));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER));
        GLIS_error_to_string_exec_GL(glBindTexture(GL_TEXTURE_2D, 0));
    } else if (IPC == IPC_MODE.socket) {
        TEXDATA = new GLuint[TEXDATA_LEN];
//        X2 = GLIS_new_socket("Compositor");
//        assert(X2 != nullptr);
//        assert(X2->bindToSocket());
//        assert(X2->listenToSocket());
//        assert(X2->acceptFromSocket());
//        assert(X2->receive(TEXDATA, TEXDATA_LEN));
        GLIS_error_to_string_exec_GL(glGenTextures(1, &GLIS_current_texture));
        GLIS_error_to_string_exec_GL(glBindTexture(GL_TEXTURE_2D, GLIS_current_texture));
        GLIS_error_to_string_exec_GL(glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, texture_width, texture_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, TEXDATA));
        delete TEXDATA;
        GLIS_error_to_string_exec_GL(glGenerateMipmap(GL_TEXTURE_2D));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER));
        GLIS_error_to_string_exec_GL(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER));
        GLIS_error_to_string_exec_GL(glBindTexture(GL_TEXTURE_2D, 0));
    }
    LOG_INFO("acquired uploaded texture");

};

#endif //GLNE_GLIS_H
